const defaultIR = {
  irVersion: '1.0',
  metadata: {
    name: 'visual-builder-demo',
    description: 'Generated by local visual builder',
  },
  runtime: {
    defaultTarget: 'local-simulation',
    targets: {
      'local-simulation': {
        rpcs: [
          {
            chainName: 'ethereum-testnet-sepolia',
            url: 'https://ethereum-sepolia-rpc.publicnode.com',
          },
        ],
      },
    },
  },
  triggers: [
    {
      id: 'trigger_1',
      name: 'Cron Trigger',
      type: 'cron',
      schedule: '0 */5 * * * *',
    },
  ],
  actions: [
    {
      id: 'action_1',
      name: 'HTTP Fetch',
      type: 'httpFetch',
      method: 'GET',
      url: 'https://api.coingecko.com/api/v3/ping',
      consensus: 'identical',
    },
    {
      id: 'action_2',
      name: 'Transform',
      type: 'transform',
      template: {
        timestamp: '$runtime.now',
        body: '$outputs.action_1.body',
      },
    },
  ],
  edges: [
    { from: 'trigger_1', to: 'action_1' },
    { from: 'action_1', to: 'action_2' },
  ],
}

let ir = structuredClone(defaultIR)

const jsonText = document.getElementById('ir-json')
const outputEl = document.getElementById('output')
const edgeFrom = document.getElementById('edge-from')
const edgeTo = document.getElementById('edge-to')
const canvas = document.getElementById('canvas')

function writeOutput(title, data) {
  outputEl.textContent = `${title}\n\n${typeof data === 'string' ? data : JSON.stringify(data, null, 2)}`
}

function syncJSON() {
  jsonText.value = JSON.stringify(ir, null, 2)
}

function syncFromJSON() {
  try {
    ir = JSON.parse(jsonText.value)
    render()
  } catch (error) {
    writeOutput('JSON parse error', error.message)
  }
}

function allNodes() {
  return [...ir.triggers, ...ir.actions]
}

function refreshEdgeSelectors() {
  const options = allNodes()
    .map((n) => `<option value="${n.id}">${n.id}</option>`)
    .join('')
  edgeFrom.innerHTML = options
  edgeTo.innerHTML = options
}

function drawEdges(nodesById) {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
  svg.style.position = 'absolute'
  svg.style.inset = '0'
  svg.style.width = '100%'
  svg.style.height = '100%'

  for (const edge of ir.edges) {
    const from = nodesById.get(edge.from)
    const to = nodesById.get(edge.to)
    if (!from || !to) continue

    const x1 = from.x + 180
    const y1 = from.y + 26
    const x2 = to.x
    const y2 = to.y + 26

    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path')
    path.setAttribute('class', 'edge')
    path.setAttribute('d', `M ${x1} ${y1} C ${x1 + 50} ${y1}, ${x2 - 50} ${y2}, ${x2} ${y2}`)
    svg.appendChild(path)
  }

  canvas.appendChild(svg)
}

function render() {
  canvas.innerHTML = ''
  refreshEdgeSelectors()
  syncJSON()

  const nodes = allNodes()
  const nodesById = new Map()

  let triggerIndex = 0
  let actionIndex = 0

  for (const node of nodes) {
    const div = document.createElement('div')
    const isTrigger = ['cron', 'http', 'evmLog'].includes(node.type)
    div.className = `node ${isTrigger ? 'trigger' : 'action'}`

    const x = isTrigger ? 16 : 290 + (actionIndex % 3) * 220
    const y = isTrigger ? 16 + triggerIndex * 90 : 16 + Math.floor(actionIndex / 3) * 100

    if (isTrigger) triggerIndex += 1
    else actionIndex += 1

    div.style.left = `${x}px`
    div.style.top = `${y}px`

    div.innerHTML = `<h4>${node.name}</h4><p>${node.id} · ${node.type}</p>`

    div.addEventListener('click', () => {
      document.getElementById('selection').textContent = `Selected ${node.id} (${node.type})`
    })

    nodesById.set(node.id, { x, y })
    canvas.appendChild(div)
  }

  drawEdges(nodesById)
}

function makeNode(type) {
  const idx = allNodes().length + 1
  const id = `${['cron', 'http', 'evmLog'].includes(type) ? 'trigger' : 'action'}_${idx}`

  if (type === 'cron') {
    return { id, name: 'Cron Trigger', type: 'cron', schedule: '0 */10 * * * *' }
  }

  if (type === 'http') {
    return { id, name: 'HTTP Trigger', type: 'http', authMode: 'none' }
  }

  if (type === 'evmLog') {
    return {
      id,
      name: 'EVM Log Trigger',
      type: 'evmLog',
      chainName: 'ethereum-testnet-sepolia',
      addresses: ['0x0000000000000000000000000000000000000001'],
    }
  }

  if (type === 'httpFetch') {
    return {
      id,
      name: 'HTTP Fetch',
      type: 'httpFetch',
      method: 'GET',
      url: 'https://api.coingecko.com/api/v3/ping',
      consensus: 'identical',
    }
  }

  if (type === 'evmRead') {
    return {
      id,
      name: 'EVM Read',
      type: 'evmRead',
      chainName: 'ethereum-testnet-sepolia',
      contractAddress: '0x0000000000000000000000000000000000000001',
      functionName: 'totalSupply',
      inputs: [],
      outputs: [{ name: 'supply', type: 'uint256' }],
      args: [],
      consensus: 'identical',
    }
  }

  if (type === 'evmWrite') {
    return {
      id,
      name: 'EVM Write',
      type: 'evmWrite',
      chainName: 'ethereum-testnet-sepolia',
      receiver: '0x0000000000000000000000000000000000000002',
      payloadPath: '$outputs.action_1',
      gasLimit: 300000,
    }
  }

  if (type === 'consensus') {
    return {
      id,
      name: 'Consensus',
      type: 'consensus',
      strategy: 'identical',
    }
  }

  return {
    id,
    name: 'Transform',
    type: 'transform',
    template: { value: '$trigger' },
  }
}

async function postJSON(url, body) {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  const payload = await res.json()
  if (!res.ok) {
    throw new Error(JSON.stringify(payload, null, 2))
  }
  return payload
}

document.querySelectorAll('[data-node]').forEach((btn) => {
  btn.addEventListener('click', () => {
    const type = btn.getAttribute('data-node')
    const node = makeNode(type)
    if (['cron', 'http', 'evmLog'].includes(type)) ir.triggers.push(node)
    else ir.actions.push(node)
    render()
  })
})

document.getElementById('add-edge').addEventListener('click', () => {
  ir.edges.push({ from: edgeFrom.value, to: edgeTo.value })
  render()
})

jsonText.addEventListener('change', syncFromJSON)

document.getElementById('validate-btn').addEventListener('click', async () => {
  try {
    syncFromJSON()
    const res = await postJSON('/api/validate', ir)
    writeOutput('Validation + preflight', res)
  } catch (error) {
    writeOutput('Validation failed', error.message)
  }
})

document.getElementById('compile-btn').addEventListener('click', async () => {
  try {
    syncFromJSON()
    const res = await postJSON('/api/compile', { ir })
    writeOutput('Compile success', res)
  } catch (error) {
    writeOutput('Compile failed', error.message)
  }
})

document.getElementById('simulate-btn').addEventListener('click', async () => {
  try {
    syncFromJSON()
    const workflowPath = `${window.location.origin.replace(/^https?:\/\//, '')}`
    const res = await postJSON('/api/simulate', {
      workflowPath: './generated/' + ir.metadata.name,
      target: ir.runtime.defaultTarget,
      triggerInput: { mode: 'interactive' },
    })
    writeOutput('Simulation', res)
  } catch (error) {
    writeOutput('Simulation failed', error.message)
  }
})

document.getElementById('generate-ai').addEventListener('click', async () => {
  try {
    const prompt = document.getElementById('ai-prompt').value.trim()
    if (!prompt) {
      writeOutput('AI', 'Prompt required')
      return
    }

    const res = await postJSON('/api/ai/generate', {
      prompt,
      context: { targetName: ir.runtime.defaultTarget },
    })

    ir = res.ir
    render()
    writeOutput('AI generate', res)
  } catch (error) {
    writeOutput('AI generate failed', error.message)
  }
})

document.getElementById('repair-btn').addEventListener('click', async () => {
  try {
    syncFromJSON()
    const validated = await postJSON('/api/validate', ir).catch((e) => {
      const parsed = JSON.parse(String(e.message))
      return parsed
    })

    const res = await postJSON('/api/ai/repair', {
      ir,
      diagnostics: validated.diagnostics || [],
    })

    ir = res.ir
    render()
    writeOutput('AI repair', res)
  } catch (error) {
    writeOutput('AI repair failed', error.message)
  }
})

render()
