import type { RuntimeConfig, TargetConfig, WorkflowIR } from '../types/workflow'
import {
  SEPOLIA_CHAIN_NAME,
  SEPOLIA_PRODUCTION_RECEIVER,
  SEPOLIA_RPC_URL,
  SEPOLIA_SIMULATION_RECEIVER,
  DEFAULT_TOKEN_ADDRESS,
  DEFAULT_TOKEN_DECIMALS,
} from './constants'

export function buildDefaultTargets(): Record<string, TargetConfig> {
  return {
    'local-simulation': {
      rpcs: [{ chainName: SEPOLIA_CHAIN_NAME, url: SEPOLIA_RPC_URL }],
      broadcast: false,
      receiverContract: SEPOLIA_SIMULATION_RECEIVER,
      chainExplorerTxBaseUrl: 'https://sepolia.etherscan.io/tx/',
    },
    'sepolia-broadcast': {
      rpcs: [{ chainName: SEPOLIA_CHAIN_NAME, url: SEPOLIA_RPC_URL }],
      broadcast: true,
      receiverContract: SEPOLIA_SIMULATION_RECEIVER,
      chainExplorerTxBaseUrl: 'https://sepolia.etherscan.io/tx/',
    },
    'sepolia-production': {
      rpcs: [{ chainName: SEPOLIA_CHAIN_NAME, url: SEPOLIA_RPC_URL }],
      broadcast: false,
      receiverContract: SEPOLIA_PRODUCTION_RECEIVER,
      chainExplorerTxBaseUrl: 'https://sepolia.etherscan.io/tx/',
    },
  }
}

export function ensureRuntimeTargets(runtime: unknown): RuntimeConfig {
  const defaults = buildDefaultTargets()
  const next: RuntimeConfig =
    runtime && typeof runtime === 'object'
      ? structuredClone(runtime as RuntimeConfig)
      : { defaultTarget: 'local-simulation', targets: {} }

  if (typeof next.defaultTarget !== 'string') next.defaultTarget = 'local-simulation'
  if (!next.targets || typeof next.targets !== 'object') next.targets = {}

  for (const [target, cfg] of Object.entries(defaults)) {
    const current = next.targets[target]
    if (!current || typeof current !== 'object') {
      next.targets[target] = structuredClone(cfg)
      continue
    }
    if (!Array.isArray(current.rpcs) || current.rpcs.length === 0) {
      current.rpcs = structuredClone(cfg.rpcs)
    }
    if (typeof current.broadcast !== 'boolean') current.broadcast = cfg.broadcast
    if (typeof current.receiverContract !== 'string') current.receiverContract = cfg.receiverContract
    if (typeof current.chainExplorerTxBaseUrl !== 'string') {
      current.chainExplorerTxBaseUrl = cfg.chainExplorerTxBaseUrl
    }
  }

  return next
}

export function normalizeLocalIR(input: unknown): WorkflowIR {
  if (!input || typeof input !== 'object') return input as WorkflowIR
  const next = structuredClone(input) as WorkflowIR
  next.runtime = ensureRuntimeTargets(next.runtime)

  if (Array.isArray(next.actions)) {
    for (const action of next.actions) {
      if (!action || typeof action !== 'object') continue
      if (action.type === 'erc20Transfer') {
        if (typeof action.tokenAddress !== 'string') action.tokenAddress = DEFAULT_TOKEN_ADDRESS
        if (typeof action.receiverContract !== 'string') {
          action.receiverContract =
            next.runtime.targets[next.runtime.defaultTarget]?.receiverContract || SEPOLIA_SIMULATION_RECEIVER
        }
        if (!Number.isInteger(action.tokenDecimals)) action.tokenDecimals = DEFAULT_TOKEN_DECIMALS
        continue
      }
      if (action.type !== 'evmPayoutTransfer') continue
      action.type = 'erc20Transfer'
      if (typeof action.name === 'string' && action.name.toLowerCase().includes('payout')) {
        action.name = 'ERC20 Transfer'
      }
      if (typeof action.tokenAddress !== 'string') action.tokenAddress = DEFAULT_TOKEN_ADDRESS
      if (typeof action.receiverContract !== 'string') {
        action.receiverContract =
          next.runtime.targets[next.runtime.defaultTarget]?.receiverContract || SEPOLIA_SIMULATION_RECEIVER
      }
      if (!Number.isInteger(action.tokenDecimals)) action.tokenDecimals = DEFAULT_TOKEN_DECIMALS
    }
  }

  return next
}

export const defaultIR: WorkflowIR = {
  irVersion: '1.0',
  metadata: {
    name: 'visual-builder-demo',
    description: 'Generated by local visual builder',
  },
  runtime: {
    defaultTarget: 'local-simulation',
    targets: buildDefaultTargets(),
  },
  triggers: [],
  actions: [],
  edges: [],
}
